# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperSecurity.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 882)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Encryption_Tab = QtWidgets.QWidget()
        self.Encryption_Tab.setObjectName("Encryption_Tab")
        self.PlainText = QtWidgets.QLabel(self.Encryption_Tab)
        self.PlainText.setGeometry(QtCore.QRect(80, 20, 121, 31))
        self.PlainText.setObjectName("PlainText")
        self.Key = QtWidgets.QLabel(self.Encryption_Tab)
        self.Key.setGeometry(QtCore.QRect(110, 370, 31, 31))
        self.Key.setObjectName("Key")
        self.PlainText_scrollArea = QtWidgets.QScrollArea(self.Encryption_Tab)
        self.PlainText_scrollArea.setGeometry(QtCore.QRect(80, 60, 941, 212))
        self.PlainText_scrollArea.setWidgetResizable(True)
        self.PlainText_scrollArea.setObjectName("PlainText_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PlainText_Input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.PlainText_Input.setCenterOnScroll(False)
        self.PlainText_Input.setObjectName("PlainText_Input")
        self.horizontalLayout.addWidget(self.PlainText_Input)
        self.PlainText_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Flie = QtWidgets.QLabel(self.Encryption_Tab)
        self.Flie.setGeometry(QtCore.QRect(110, 300, 31, 31))
        self.Flie.setObjectName("Flie")
        self.FilePath_Input = QtWidgets.QLineEdit(self.Encryption_Tab)
        self.FilePath_Input.setGeometry(QtCore.QRect(180, 300, 671, 23))
        self.FilePath_Input.setObjectName("FilePath_Input")
        self.Key_Input = QtWidgets.QLineEdit(self.Encryption_Tab)
        self.Key_Input.setGeometry(QtCore.QRect(180, 370, 671, 23))
        self.Key_Input.setObjectName("Key_Input")
        self.Algorithm = QtWidgets.QLabel(self.Encryption_Tab)
        self.Algorithm.setGeometry(QtCore.QRect(80, 420, 71, 16))
        self.Algorithm.setObjectName("Algorithm")
        self.CipherText = QtWidgets.QLabel(self.Encryption_Tab)
        self.CipherText.setGeometry(QtCore.QRect(80, 460, 81, 16))
        self.CipherText.setObjectName("CipherText")
        self.CipherText_scrollArea = QtWidgets.QScrollArea(self.Encryption_Tab)
        self.CipherText_scrollArea.setGeometry(QtCore.QRect(80, 490, 941, 212))
        self.CipherText_scrollArea.setWidgetResizable(True)
        self.CipherText_scrollArea.setObjectName("CipherText_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CipherText_Output = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.CipherText_Output.setReadOnly(True)
        self.CipherText_Output.setObjectName("CipherText_Output")
        self.horizontalLayout_2.addWidget(self.CipherText_Output)
        self.CipherText_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.Encrypto_Button = QtWidgets.QPushButton(self.Encryption_Tab)
        self.Encrypto_Button.setGeometry(QtCore.QRect(350, 730, 101, 31))
        self.Encrypto_Button.setObjectName("Encrypto_Button")
        self.Caesar_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Caesar_Box.setGeometry(QtCore.QRect(200, 420, 101, 21))
        self.Caesar_Box.setObjectName("Caesar_Box")
        self.Keyword_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Keyword_Box.setGeometry(QtCore.QRect(340, 420, 85, 21))
        self.Keyword_Box.setObjectName("Keyword_Box")
        self.Permutation_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Permutation_Box.setGeometry(QtCore.QRect(470, 420, 111, 21))
        self.Permutation_Box.setObjectName("Permutation_Box")
        self.DoubleTransposition_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.DoubleTransposition_Box.setGeometry(QtCore.QRect(680, 460, 151, 21))
        self.DoubleTransposition_Box.setObjectName("DoubleTransposition_Box")
        self.Vigenere_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Vigenere_Box.setGeometry(QtCore.QRect(720, 420, 85, 21))
        self.Vigenere_Box.setObjectName("Vigenere_Box")
        self.Autokey_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Autokey_Box.setGeometry(QtCore.QRect(820, 420, 85, 21))
        self.Autokey_Box.setObjectName("Autokey_Box")
        self.Playfair_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Playfair_Box.setGeometry(QtCore.QRect(250, 460, 85, 21))
        self.Playfair_Box.setObjectName("Playfair_Box")
        self.RSA_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.RSA_Box.setGeometry(QtCore.QRect(560, 460, 85, 21))
        self.RSA_Box.setObjectName("RSA_Box")
        self.CA_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.CA_Box.setGeometry(QtCore.QRect(430, 460, 85, 21))
        self.CA_Box.setObjectName("CA_Box")
        self.AES_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.AES_Box.setGeometry(QtCore.QRect(620, 420, 85, 21))
        self.AES_Box.setObjectName("AES_Box")
        self.SendToRemote_Button = QtWidgets.QPushButton(self.Encryption_Tab)
        self.SendToRemote_Button.setGeometry(QtCore.QRect(640, 730, 111, 31))
        self.SendToRemote_Button.setObjectName("SendToRemote_Button")
        self.tabWidget.addTab(self.Encryption_Tab, "")
        self.Decryption_Tab = QtWidgets.QWidget()
        self.Decryption_Tab.setObjectName("Decryption_Tab")
        self.CipherText_scrollArea_2 = QtWidgets.QScrollArea(self.Decryption_Tab)
        self.CipherText_scrollArea_2.setGeometry(QtCore.QRect(80, 60, 941, 212))
        self.CipherText_scrollArea_2.setWidgetResizable(True)
        self.CipherText_scrollArea_2.setObjectName("CipherText_scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CiperText_Input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.CiperText_Input.setCenterOnScroll(False)
        self.CiperText_Input.setObjectName("CiperText_Input")
        self.horizontalLayout_3.addWidget(self.CiperText_Input)
        self.CipherText_scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label_9 = QtWidgets.QLabel(self.Decryption_Tab)
        self.label_9.setGeometry(QtCore.QRect(100, 420, 71, 16))
        self.label_9.setObjectName("label_9")
        self.Caesar_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Caesar_Box_2.setGeometry(QtCore.QRect(210, 420, 101, 21))
        self.Caesar_Box_2.setObjectName("Caesar_Box_2")
        self.Keyword_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Keyword_Box_2.setGeometry(QtCore.QRect(330, 420, 85, 21))
        self.Keyword_Box_2.setObjectName("Keyword_Box_2")
        self.PlainText_scrollAera = QtWidgets.QScrollArea(self.Decryption_Tab)
        self.PlainText_scrollAera.setGeometry(QtCore.QRect(80, 510, 941, 212))
        self.PlainText_scrollAera.setWidgetResizable(True)
        self.PlainText_scrollAera.setObjectName("PlainText_scrollAera")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PlainText_Output = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_7)
        self.PlainText_Output.setReadOnly(True)
        self.PlainText_Output.setObjectName("PlainText_Output")
        self.horizontalLayout_7.addWidget(self.PlainText_Output)
        self.PlainText_scrollAera.setWidget(self.scrollAreaWidgetContents_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.Decryption_Tab)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 740, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Permutation_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Permutation_Box_2.setGeometry(QtCore.QRect(470, 420, 111, 21))
        self.Permutation_Box_2.setObjectName("Permutation_Box_2")
        self.AES_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.AES_Box_2.setGeometry(QtCore.QRect(620, 420, 85, 21))
        self.AES_Box_2.setObjectName("AES_Box_2")
        self.Vigenere_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Vigenere_Box_2.setGeometry(QtCore.QRect(740, 420, 85, 21))
        self.Vigenere_Box_2.setObjectName("Vigenere_Box_2")
        self.Autokey_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Autokey_Box_2.setGeometry(QtCore.QRect(880, 420, 85, 21))
        self.Autokey_Box_2.setObjectName("Autokey_Box_2")
        self.Playfair_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.Playfair_Box_2.setGeometry(QtCore.QRect(300, 470, 85, 21))
        self.Playfair_Box_2.setObjectName("Playfair_Box_2")
        self.CA_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.CA_Box_2.setGeometry(QtCore.QRect(440, 470, 85, 21))
        self.CA_Box_2.setObjectName("CA_Box_2")
        self.RSA_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.RSA_Box_2.setGeometry(QtCore.QRect(570, 470, 85, 21))
        self.RSA_Box_2.setObjectName("RSA_Box_2")
        self.DoubleTransposition_Box_2 = QtWidgets.QCheckBox(self.Decryption_Tab)
        self.DoubleTransposition_Box_2.setGeometry(QtCore.QRect(690, 470, 151, 21))
        self.DoubleTransposition_Box_2.setObjectName("DoubleTransposition_Box_2")
        self.CipherText_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.CipherText_2.setGeometry(QtCore.QRect(80, 30, 81, 16))
        self.CipherText_2.setObjectName("CipherText_2")
        self.PlainText_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.PlainText_2.setGeometry(QtCore.QRect(80, 470, 121, 31))
        self.PlainText_2.setObjectName("PlainText_2")
        self.Flie_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.Flie_2.setGeometry(QtCore.QRect(140, 310, 31, 31))
        self.Flie_2.setObjectName("Flie_2")
        self.Key_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.Key_2.setGeometry(QtCore.QRect(140, 370, 31, 31))
        self.Key_2.setObjectName("Key_2")
        self.FilePath_Input_2 = QtWidgets.QLineEdit(self.Decryption_Tab)
        self.FilePath_Input_2.setGeometry(QtCore.QRect(200, 310, 671, 23))
        self.FilePath_Input_2.setObjectName("FilePath_Input_2")
        self.Key_Input_2 = QtWidgets.QLineEdit(self.Decryption_Tab)
        self.Key_Input_2.setGeometry(QtCore.QRect(200, 370, 671, 23))
        self.Key_Input_2.setObjectName("Key_Input_2")
        self.tabWidget.addTab(self.Decryption_Tab, "")
        self.DHKeyExchange_Tab = QtWidgets.QWidget()
        self.DHKeyExchange_Tab.setObjectName("DHKeyExchange_Tab")
        self.RandomGenerate_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.RandomGenerate_Button.setGeometry(QtCore.QRect(40, 300, 121, 61))
        self.RandomGenerate_Button.setObjectName("RandomGenerate_Button")
        self.GeneratePubKey_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.GeneratePubKey_Button.setGeometry(QtCore.QRect(190, 300, 121, 61))
        self.GeneratePubKey_Button.setObjectName("GeneratePubKey_Button")
        self.p_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.p_label.setGeometry(QtCore.QRect(90, 110, 59, 15))
        self.p_label.setObjectName("p_label")
        self.g_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.g_label.setGeometry(QtCore.QRect(90, 160, 61, 20))
        self.g_label.setObjectName("g_label")
        self.a_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.a_label.setGeometry(QtCore.QRect(90, 220, 59, 15))
        self.a_label.setObjectName("a_label")
        self.p_Inputline = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.p_Inputline.setGeometry(QtCore.QRect(170, 110, 113, 23))
        self.p_Inputline.setObjectName("p_Inputline")
        self.g_Inputline = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.g_Inputline.setGeometry(QtCore.QRect(170, 160, 113, 23))
        self.g_Inputline.setObjectName("g_Inputline")
        self.a_Inputline = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.a_Inputline.setGeometry(QtCore.QRect(170, 220, 113, 23))
        self.a_Inputline.setObjectName("a_Inputline")
        self.LocalPubKey_Input_2 = QtWidgets.QPlainTextEdit(self.DHKeyExchange_Tab)
        self.LocalPubKey_Input_2.setGeometry(QtCore.QRect(150, 430, 231, 31))
        self.LocalPubKey_Input_2.setObjectName("LocalPubKey_Input_2")
        self.SendPubKey_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.SendPubKey_Button.setGeometry(QtCore.QRect(200, 560, 121, 61))
        self.SendPubKey_Button.setObjectName("SendPubKey_Button")
        self.LocalPubKey_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.LocalPubKey_label.setGeometry(QtCore.QRect(50, 430, 91, 20))
        self.LocalPubKey_label.setObjectName("LocalPubKey_label")
        self.ConnectRemote_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.ConnectRemote_Button.setGeometry(QtCore.QRect(660, 210, 121, 31))
        self.ConnectRemote_Button.setObjectName("ConnectRemote_Button")
        self.RemoteAddress_Input = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.RemoteAddress_Input.setGeometry(QtCore.QRect(720, 100, 181, 23))
        self.RemoteAddress_Input.setObjectName("RemoteAddress_Input")
        self.RemotePort_Input = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.RemotePort_Input.setGeometry(QtCore.QRect(720, 150, 181, 23))
        self.RemotePort_Input.setObjectName("RemotePort_Input")
        self.RemoteAddress_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.RemoteAddress_label.setGeometry(QtCore.QRect(610, 100, 101, 16))
        self.RemoteAddress_label.setObjectName("RemoteAddress_label")
        self.RemotePort_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.RemotePort_label.setGeometry(QtCore.QRect(630, 150, 81, 20))
        self.RemotePort_label.setObjectName("RemotePort_label")
        self.CommunicationLog_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.CommunicationLog_label.setGeometry(QtCore.QRect(610, 390, 121, 31))
        self.CommunicationLog_label.setObjectName("CommunicationLog_label")
        self.DisconnectRemote_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.DisconnectRemote_Button.setGeometry(QtCore.QRect(840, 210, 121, 31))
        self.DisconnectRemote_Button.setObjectName("DisconnectRemote_Button")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.DHKeyExchange_Tab)
        self.scrollArea_8.setGeometry(QtCore.QRect(610, 440, 391, 341))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 389, 339))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Log_Output = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_8)
        self.Log_Output.setObjectName("Log_Output")
        self.horizontalLayout_8.addWidget(self.Log_Output)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.State_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.State_label.setGeometry(QtCore.QRect(320, 30, 141, 41))
        self.State_label.setObjectName("State_label")
        self.ListenAddress_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.ListenAddress_label.setGeometry(QtCore.QRect(610, 260, 101, 16))
        self.ListenAddress_label.setObjectName("ListenAddress_label")
        self.ListenAddress_Input = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.ListenAddress_Input.setGeometry(QtCore.QRect(720, 260, 181, 23))
        self.ListenAddress_Input.setObjectName("ListenAddress_Input")
        self.ListenPort_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.ListenPort_label.setGeometry(QtCore.QRect(640, 310, 81, 20))
        self.ListenPort_label.setObjectName("ListenPort_label")
        self.ListenPort_Input = QtWidgets.QLineEdit(self.DHKeyExchange_Tab)
        self.ListenPort_Input.setGeometry(QtCore.QRect(722, 310, 181, 23))
        self.ListenPort_Input.setObjectName("ListenPort_Input")
        self.StartListen_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.StartListen_Button.setGeometry(QtCore.QRect(660, 350, 101, 31))
        self.StartListen_Button.setObjectName("StartListen_Button")
        self.StopListen_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.StopListen_Button.setGeometry(QtCore.QRect(820, 350, 101, 31))
        self.StopListen_Button.setObjectName("StopListen_Button")
        self.RemotePubKey_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.RemotePubKey_label.setGeometry(QtCore.QRect(30, 500, 101, 20))
        self.RemotePubKey_label.setObjectName("RemotePubKey_label")
        self.RemotePubKey_Input = QtWidgets.QPlainTextEdit(self.DHKeyExchange_Tab)
        self.RemotePubKey_Input.setGeometry(QtCore.QRect(150, 500, 231, 31))
        self.RemotePubKey_Input.setObjectName("RemotePubKey_Input")
        self.GeneratedKey_label = QtWidgets.QLabel(self.DHKeyExchange_Tab)
        self.GeneratedKey_label.setGeometry(QtCore.QRect(50, 650, 91, 20))
        self.GeneratedKey_label.setObjectName("GeneratedKey_label")
        self.GeneratedPubKey_Output = QtWidgets.QPlainTextEdit(self.DHKeyExchange_Tab)
        self.GeneratedPubKey_Output.setGeometry(QtCore.QRect(160, 650, 231, 31))
        self.GeneratedPubKey_Output.setObjectName("GeneratedPubKey_Output")
        self.GenerateKey_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.GenerateKey_Button.setGeometry(QtCore.QRect(200, 710, 121, 61))
        self.GenerateKey_Button.setObjectName("GenerateKey_Button")
        self.SendPG_Button = QtWidgets.QPushButton(self.DHKeyExchange_Tab)
        self.SendPG_Button.setGeometry(QtCore.QRect(350, 300, 111, 61))
        self.SendPG_Button.setObjectName("SendPG_Button")
        self.tabWidget.addTab(self.DHKeyExchange_Tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlainText.setText(_translate("MainWindow", "PlainText:"))
        self.Key.setText(_translate("MainWindow", "Key:"))
        self.Flie.setText(_translate("MainWindow", "File:"))
        self.Algorithm.setText(_translate("MainWindow", "Algorithm:"))
        self.CipherText.setText(_translate("MainWindow", "CipherText:"))
        self.Encrypto_Button.setText(_translate("MainWindow", "Encrypto"))
        self.Caesar_Box.setText(_translate("MainWindow", "Caesar"))
        self.Keyword_Box.setText(_translate("MainWindow", "Keyword"))
        self.Permutation_Box.setText(_translate("MainWindow", "Permutation "))
        self.DoubleTransposition_Box.setText(_translate("MainWindow", "Double-Transposition"))
        self.Vigenere_Box.setText(_translate("MainWindow", "Vigenere"))
        self.Autokey_Box.setText(_translate("MainWindow", "Autokey "))
        self.Playfair_Box.setText(_translate("MainWindow", "Playfair "))
        self.RSA_Box.setText(_translate("MainWindow", "RSA"))
        self.CA_Box.setText(_translate("MainWindow", "CA "))
        self.AES_Box.setText(_translate("MainWindow", "AES"))
        self.SendToRemote_Button.setText(_translate("MainWindow", "SendToRemote"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Encryption_Tab), _translate("MainWindow", "Encrypttion"))
        self.label_9.setText(_translate("MainWindow", "Algorithm:"))
        self.Caesar_Box_2.setText(_translate("MainWindow", "Caesar"))
        self.Keyword_Box_2.setText(_translate("MainWindow", "Keyword"))
        self.pushButton_3.setText(_translate("MainWindow", "Decrypto"))
        self.Permutation_Box_2.setText(_translate("MainWindow", "Permutation "))
        self.AES_Box_2.setText(_translate("MainWindow", "AES"))
        self.Vigenere_Box_2.setText(_translate("MainWindow", "Vigenere"))
        self.Autokey_Box_2.setText(_translate("MainWindow", "Autokey "))
        self.Playfair_Box_2.setText(_translate("MainWindow", "Playfair "))
        self.CA_Box_2.setText(_translate("MainWindow", "CA "))
        self.RSA_Box_2.setText(_translate("MainWindow", "RSA"))
        self.DoubleTransposition_Box_2.setText(_translate("MainWindow", "Double-Transposition"))
        self.CipherText_2.setText(_translate("MainWindow", "CipherText:"))
        self.PlainText_2.setText(_translate("MainWindow", "PlainText:"))
        self.Flie_2.setText(_translate("MainWindow", "File:"))
        self.Key_2.setText(_translate("MainWindow", "Key:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Decryption_Tab), _translate("MainWindow", "Decryption"))
        self.RandomGenerate_Button.setText(_translate("MainWindow", "RandomGenerate"))
        self.GeneratePubKey_Button.setText(_translate("MainWindow", "GeneratePubKey"))
        self.p_label.setText(_translate("MainWindow", "p:"))
        self.g_label.setText(_translate("MainWindow", "g:"))
        self.a_label.setText(_translate("MainWindow", "a:"))
        self.SendPubKey_Button.setText(_translate("MainWindow", "SendPubKey"))
        self.LocalPubKey_label.setText(_translate("MainWindow", "LocalPubKey:"))
        self.ConnectRemote_Button.setText(_translate("MainWindow", "ConnectRemote"))
        self.RemoteAddress_label.setText(_translate("MainWindow", "RemoteAddress:"))
        self.RemotePort_label.setText(_translate("MainWindow", "RemotePort:"))
        self.CommunicationLog_label.setText(_translate("MainWindow", "CommunicationLog:"))
        self.DisconnectRemote_Button.setText(_translate("MainWindow", "DisconnectRemote"))
        self.State_label.setText(_translate("MainWindow", "State:"))
        self.ListenAddress_label.setText(_translate("MainWindow", "ListenAddress:"))
        self.ListenPort_label.setText(_translate("MainWindow", "ListenPort:"))
        self.StartListen_Button.setText(_translate("MainWindow", "StartListening"))
        self.StopListen_Button.setText(_translate("MainWindow", "StopListening"))
        self.RemotePubKey_label.setText(_translate("MainWindow", "RemotePubKey:"))
        self.GeneratedKey_label.setText(_translate("MainWindow", "GeneratedKey:"))
        self.GenerateKey_Button.setText(_translate("MainWindow", "GenerateKey"))
        self.SendPG_Button.setText(_translate("MainWindow", "SendPG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DHKeyExchange_Tab), _translate("MainWindow", "DHKeyExchange"))
        

