# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperSecurity.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Encryption_Tab = QtWidgets.QWidget()
        self.Encryption_Tab.setObjectName("Encryption_Tab")
        self.PlainText = QtWidgets.QLabel(self.Encryption_Tab)
        self.PlainText.setGeometry(QtCore.QRect(80, 20, 121, 31))
        self.PlainText.setObjectName("PlainText")
        self.Key = QtWidgets.QLabel(self.Encryption_Tab)
        self.Key.setGeometry(QtCore.QRect(110, 370, 31, 31))
        self.Key.setObjectName("Key")
        self.PlainText_scrollArea = QtWidgets.QScrollArea(self.Encryption_Tab)
        self.PlainText_scrollArea.setGeometry(QtCore.QRect(80, 60, 941, 212))
        self.PlainText_scrollArea.setWidgetResizable(True)
        self.PlainText_scrollArea.setObjectName("PlainText_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PlainText_Input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.PlainText_Input.setCenterOnScroll(False)
        self.PlainText_Input.setObjectName("PlainText_Input")
        self.horizontalLayout.addWidget(self.PlainText_Input)
        self.PlainText_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Flie = QtWidgets.QLabel(self.Encryption_Tab)
        self.Flie.setGeometry(QtCore.QRect(110, 300, 31, 31))
        self.Flie.setObjectName("Flie")
        self.FilePath_Input = QtWidgets.QLineEdit(self.Encryption_Tab)
        self.FilePath_Input.setGeometry(QtCore.QRect(180, 300, 671, 23))
        self.FilePath_Input.setObjectName("FilePath_Input")
        self.Key_Input = QtWidgets.QLineEdit(self.Encryption_Tab)
        self.Key_Input.setGeometry(QtCore.QRect(180, 370, 671, 23))
        self.Key_Input.setObjectName("Key_Input")
        self.Algorithm = QtWidgets.QLabel(self.Encryption_Tab)
        self.Algorithm.setGeometry(QtCore.QRect(80, 420, 71, 16))
        self.Algorithm.setObjectName("Algorithm")
        self.CipherText = QtWidgets.QLabel(self.Encryption_Tab)
        self.CipherText.setGeometry(QtCore.QRect(80, 460, 81, 16))
        self.CipherText.setObjectName("CipherText")
        self.CipherText_scrollArea = QtWidgets.QScrollArea(self.Encryption_Tab)
        self.CipherText_scrollArea.setGeometry(QtCore.QRect(80, 490, 941, 212))
        self.CipherText_scrollArea.setWidgetResizable(True)
        self.CipherText_scrollArea.setObjectName("CipherText_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CipherText_Output = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.CipherText_Output.setReadOnly(True)
        self.CipherText_Output.setObjectName("CipherText_Output")
        self.horizontalLayout_2.addWidget(self.CipherText_Output)
        self.CipherText_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.Encrypto_Button = QtWidgets.QPushButton(self.Encryption_Tab)
        self.Encrypto_Button.setGeometry(QtCore.QRect(480, 730, 101, 31))
        self.Encrypto_Button.setObjectName("Encrypto_Button")
        self.Caesar_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Caesar_Box.setGeometry(QtCore.QRect(200, 420, 101, 21))
        self.Caesar_Box.setObjectName("Caesar_Box")
        self.Keyword_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Keyword_Box.setGeometry(QtCore.QRect(340, 420, 85, 21))
        self.Keyword_Box.setObjectName("Keyword_Box")
        self.Permutation_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Permutation_Box.setGeometry(QtCore.QRect(470, 420, 111, 21))
        self.Permutation_Box.setObjectName("Permutation_Box")
        self.DoubleTransposition_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.DoubleTransposition_Box.setGeometry(QtCore.QRect(680, 460, 151, 21))
        self.DoubleTransposition_Box.setObjectName("DoubleTransposition_Box")
        self.Vigenere_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Vigenere_Box.setGeometry(QtCore.QRect(720, 420, 85, 21))
        self.Vigenere_Box.setObjectName("Vigenere_Box")
        self.Autokey_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Autokey_Box.setGeometry(QtCore.QRect(820, 420, 85, 21))
        self.Autokey_Box.setObjectName("Autokey_Box")
        self.Playfair_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.Playfair_Box.setGeometry(QtCore.QRect(250, 460, 85, 21))
        self.Playfair_Box.setObjectName("Playfair_Box")
        self.RSA_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.RSA_Box.setGeometry(QtCore.QRect(560, 460, 85, 21))
        self.RSA_Box.setObjectName("RSA_Box")
        self.CA_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.CA_Box.setGeometry(QtCore.QRect(430, 460, 85, 21))
        self.CA_Box.setObjectName("CA_Box")
        self.AES_Box = QtWidgets.QRadioButton(self.Encryption_Tab)
        self.AES_Box.setGeometry(QtCore.QRect(620, 420, 85, 21))
        self.AES_Box.setObjectName("AES_Box")
        self.SendToServer_Button = QtWidgets.QPushButton(self.Encryption_Tab)
        self.SendToServer_Button.setGeometry(QtCore.QRect(680, 730, 111, 31))
        self.SendToServer_Button.setObjectName("SendToServer_Button")
        self.SendToClient_Button = QtWidgets.QPushButton(self.Encryption_Tab)
        self.SendToClient_Button.setGeometry(QtCore.QRect(280, 730, 111, 31))
        self.SendToClient_Button.setObjectName("SendToClient_Button")
        self.SelectPlainTextFile = QtWidgets.QPushButton(self.Encryption_Tab)
        self.SelectPlainTextFile.setGeometry(QtCore.QRect(870, 300, 80, 23))
        self.SelectPlainTextFile.setObjectName("SelectPlainTextFile")
        self.tabWidget.addTab(self.Encryption_Tab, "")
        self.Decryption_Tab = QtWidgets.QWidget()
        self.Decryption_Tab.setObjectName("Decryption_Tab")
        self.CipherText_scrollArea_2 = QtWidgets.QScrollArea(self.Decryption_Tab)
        self.CipherText_scrollArea_2.setGeometry(QtCore.QRect(80, 60, 941, 212))
        self.CipherText_scrollArea_2.setWidgetResizable(True)
        self.CipherText_scrollArea_2.setObjectName("CipherText_scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CiperText_Input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.CiperText_Input.setCenterOnScroll(False)
        self.CiperText_Input.setObjectName("CiperText_Input")
        self.horizontalLayout_3.addWidget(self.CiperText_Input)
        self.CipherText_scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label_9 = QtWidgets.QLabel(self.Decryption_Tab)
        self.label_9.setGeometry(QtCore.QRect(100, 420, 71, 16))
        self.label_9.setObjectName("label_9")
        self.Caesar_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Caesar_Box_2.setGeometry(QtCore.QRect(210, 420, 101, 21))
        self.Caesar_Box_2.setObjectName("Caesar_Box_2")
        self.Keyword_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Keyword_Box_2.setGeometry(QtCore.QRect(330, 420, 85, 21))
        self.Keyword_Box_2.setObjectName("Keyword_Box_2")
        self.PlainText_scrollAera = QtWidgets.QScrollArea(self.Decryption_Tab)
        self.PlainText_scrollAera.setGeometry(QtCore.QRect(80, 510, 941, 212))
        self.PlainText_scrollAera.setWidgetResizable(True)
        self.PlainText_scrollAera.setObjectName("PlainText_scrollAera")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 939, 210))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PlainText_Output = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_7)
        self.PlainText_Output.setReadOnly(True)
        self.PlainText_Output.setObjectName("PlainText_Output")
        self.horizontalLayout_7.addWidget(self.PlainText_Output)
        self.PlainText_scrollAera.setWidget(self.scrollAreaWidgetContents_7)
        self.Decrypto_Button = QtWidgets.QPushButton(self.Decryption_Tab)
        self.Decrypto_Button.setGeometry(QtCore.QRect(480, 740, 101, 31))
        self.Decrypto_Button.setObjectName("Decrypto_Button")
        self.Permutation_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Permutation_Box_2.setGeometry(QtCore.QRect(470, 420, 111, 21))
        self.Permutation_Box_2.setObjectName("Permutation_Box_2")
        self.AES_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.AES_Box_2.setGeometry(QtCore.QRect(620, 420, 85, 21))
        self.AES_Box_2.setObjectName("AES_Box_2")
        self.Vigenere_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Vigenere_Box_2.setGeometry(QtCore.QRect(740, 420, 85, 21))
        self.Vigenere_Box_2.setObjectName("Vigenere_Box_2")
        self.Autokey_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Autokey_Box_2.setGeometry(QtCore.QRect(880, 420, 85, 21))
        self.Autokey_Box_2.setObjectName("Autokey_Box_2")
        self.Playfair_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.Playfair_Box_2.setGeometry(QtCore.QRect(300, 470, 85, 21))
        self.Playfair_Box_2.setObjectName("Playfair_Box_2")
        self.CA_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.CA_Box_2.setGeometry(QtCore.QRect(440, 470, 85, 21))
        self.CA_Box_2.setObjectName("CA_Box_2")
        self.RSA_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.RSA_Box_2.setGeometry(QtCore.QRect(570, 470, 85, 21))
        self.RSA_Box_2.setObjectName("RSA_Box_2")
        self.DoubleTransposition_Box_2 = QtWidgets.QRadioButton(self.Decryption_Tab)
        self.DoubleTransposition_Box_2.setGeometry(QtCore.QRect(690, 470, 151, 21))
        self.DoubleTransposition_Box_2.setObjectName("DoubleTransposition_Box_2")
        self.CipherText_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.CipherText_2.setGeometry(QtCore.QRect(80, 30, 81, 16))
        self.CipherText_2.setObjectName("CipherText_2")
        self.PlainText_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.PlainText_2.setGeometry(QtCore.QRect(80, 470, 121, 31))
        self.PlainText_2.setObjectName("PlainText_2")
        self.Flie_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.Flie_2.setGeometry(QtCore.QRect(140, 310, 31, 31))
        self.Flie_2.setObjectName("Flie_2")
        self.Key_2 = QtWidgets.QLabel(self.Decryption_Tab)
        self.Key_2.setGeometry(QtCore.QRect(140, 370, 31, 31))
        self.Key_2.setObjectName("Key_2")
        self.FilePath_Input_2 = QtWidgets.QLineEdit(self.Decryption_Tab)
        self.FilePath_Input_2.setGeometry(QtCore.QRect(200, 310, 671, 23))
        self.FilePath_Input_2.setObjectName("FilePath_Input_2")
        self.Key_Input_2 = QtWidgets.QLineEdit(self.Decryption_Tab)
        self.Key_Input_2.setGeometry(QtCore.QRect(200, 370, 671, 23))
        self.Key_Input_2.setObjectName("Key_Input_2")
        self.SelectCipherTextFile = QtWidgets.QPushButton(self.Decryption_Tab)
        self.SelectCipherTextFile.setGeometry(QtCore.QRect(890, 310, 80, 23))
        self.SelectCipherTextFile.setObjectName("SelectCipherTextFile")
        self.tabWidget.addTab(self.Decryption_Tab, "")
        self.Client_Tab = QtWidgets.QWidget()
        self.Client_Tab.setObjectName("Client_Tab")
        self.ClientRandomGenerate_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.ClientRandomGenerate_Button.setGeometry(QtCore.QRect(40, 260, 121, 61))
        self.ClientRandomGenerate_Button.setObjectName("ClientRandomGenerate_Button")
        self.ClientGeneratePubKey_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.ClientGeneratePubKey_Button.setGeometry(QtCore.QRect(190, 260, 121, 61))
        self.ClientGeneratePubKey_Button.setObjectName("ClientGeneratePubKey_Button")
        self.p_label = QtWidgets.QLabel(self.Client_Tab)
        self.p_label.setGeometry(QtCore.QRect(120, 80, 59, 15))
        self.p_label.setObjectName("p_label")
        self.g_label = QtWidgets.QLabel(self.Client_Tab)
        self.g_label.setGeometry(QtCore.QRect(120, 140, 61, 20))
        self.g_label.setObjectName("g_label")
        self.a_label = QtWidgets.QLabel(self.Client_Tab)
        self.a_label.setGeometry(QtCore.QRect(120, 210, 59, 15))
        self.a_label.setObjectName("a_label")
        self.ClientP_Inputline = QtWidgets.QLineEdit(self.Client_Tab)
        self.ClientP_Inputline.setGeometry(QtCore.QRect(190, 80, 121, 23))
        self.ClientP_Inputline.setObjectName("ClientP_Inputline")
        self.ClientG_Inputline = QtWidgets.QLineEdit(self.Client_Tab)
        self.ClientG_Inputline.setGeometry(QtCore.QRect(190, 140, 121, 23))
        self.ClientG_Inputline.setObjectName("ClientG_Inputline")
        self.ClientA_Inputline = QtWidgets.QLineEdit(self.Client_Tab)
        self.ClientA_Inputline.setGeometry(QtCore.QRect(190, 200, 121, 23))
        self.ClientA_Inputline.setObjectName("ClientA_Inputline")
        self.cClientPubKey_Input = QtWidgets.QPlainTextEdit(self.Client_Tab)
        self.cClientPubKey_Input.setGeometry(QtCore.QRect(150, 370, 231, 31))
        self.cClientPubKey_Input.setObjectName("cClientPubKey_Input")
        self.ClientSendPubKey_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.ClientSendPubKey_Button.setGeometry(QtCore.QRect(190, 500, 121, 61))
        self.ClientSendPubKey_Button.setObjectName("ClientSendPubKey_Button")
        self.cClientPubKey_label = QtWidgets.QLabel(self.Client_Tab)
        self.cClientPubKey_label.setGeometry(QtCore.QRect(50, 370, 91, 20))
        self.cClientPubKey_label.setObjectName("cClientPubKey_label")
        self.ConnectServer_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.ConnectServer_Button.setGeometry(QtCore.QRect(690, 170, 121, 31))
        self.ConnectServer_Button.setObjectName("ConnectServer_Button")
        self.ServerAddress_Input = QtWidgets.QLineEdit(self.Client_Tab)
        self.ServerAddress_Input.setGeometry(QtCore.QRect(740, 70, 181, 23))
        self.ServerAddress_Input.setObjectName("ServerAddress_Input")
        self.ServerPort_Input = QtWidgets.QLineEdit(self.Client_Tab)
        self.ServerPort_Input.setGeometry(QtCore.QRect(740, 120, 181, 23))
        self.ServerPort_Input.setObjectName("ServerPort_Input")
        self.RemotePort_label = QtWidgets.QLabel(self.Client_Tab)
        self.RemotePort_label.setGeometry(QtCore.QRect(650, 120, 81, 20))
        self.RemotePort_label.setObjectName("RemotePort_label")
        self.CommunicationLog_label = QtWidgets.QLabel(self.Client_Tab)
        self.CommunicationLog_label.setGeometry(QtCore.QRect(530, 340, 121, 31))
        self.CommunicationLog_label.setObjectName("CommunicationLog_label")
        self.DisconnectServer_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.DisconnectServer_Button.setGeometry(QtCore.QRect(860, 170, 121, 31))
        self.DisconnectServer_Button.setObjectName("DisconnectServer_Button")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.Client_Tab)
        self.scrollArea_8.setGeometry(QtCore.QRect(530, 390, 531, 361))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 529, 359))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ClientMessageBox = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_8)
        self.ClientMessageBox.setObjectName("ClientMessageBox")
        self.horizontalLayout_8.addWidget(self.ClientMessageBox)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.ClientState_label = QtWidgets.QLabel(self.Client_Tab)
        self.ClientState_label.setGeometry(QtCore.QRect(450, 20, 41, 41))
        self.ClientState_label.setObjectName("ClientState_label")
        self.RemotePubKey_label = QtWidgets.QLabel(self.Client_Tab)
        self.RemotePubKey_label.setGeometry(QtCore.QRect(40, 440, 101, 20))
        self.RemotePubKey_label.setObjectName("RemotePubKey_label")
        self.cServerPubKey_Input = QtWidgets.QPlainTextEdit(self.Client_Tab)
        self.cServerPubKey_Input.setGeometry(QtCore.QRect(150, 440, 231, 31))
        self.cServerPubKey_Input.setObjectName("cServerPubKey_Input")
        self.GeneratedKey_label = QtWidgets.QLabel(self.Client_Tab)
        self.GeneratedKey_label.setGeometry(QtCore.QRect(50, 590, 91, 20))
        self.GeneratedKey_label.setObjectName("GeneratedKey_label")
        self.ClientGeneratedPubKey_Output = QtWidgets.QPlainTextEdit(self.Client_Tab)
        self.ClientGeneratedPubKey_Output.setGeometry(QtCore.QRect(160, 590, 231, 31))
        self.ClientGeneratedPubKey_Output.setObjectName("ClientGeneratedPubKey_Output")
        self.ClientGenerateKey_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.ClientGenerateKey_Button.setGeometry(QtCore.QRect(190, 640, 121, 61))
        self.ClientGenerateKey_Button.setObjectName("ClientGenerateKey_Button")
        self.SendPG2Server_Button = QtWidgets.QPushButton(self.Client_Tab)
        self.SendPG2Server_Button.setGeometry(QtCore.QRect(350, 260, 111, 61))
        self.SendPG2Server_Button.setObjectName("SendPG2Server_Button")
        self.ClientState = QtWidgets.QLabel(self.Client_Tab)
        self.ClientState.setGeometry(QtCore.QRect(500, 30, 201, 21))
        self.ClientState.setObjectName("ClientState")
        self.RemoteAddress_label = QtWidgets.QLabel(self.Client_Tab)
        self.RemoteAddress_label.setGeometry(QtCore.QRect(630, 70, 101, 16))
        self.RemoteAddress_label.setObjectName("RemoteAddress_label")
        self.ServerObject_label = QtWidgets.QLabel(self.Client_Tab)
        self.ServerObject_label.setGeometry(QtCore.QRect(640, 220, 81, 41))
        self.ServerObject_label.setObjectName("ServerObject_label")
        self.ServerObject_ComBox = QtWidgets.QComboBox(self.Client_Tab)
        self.ServerObject_ComBox.setGeometry(QtCore.QRect(740, 230, 181, 23))
        self.ServerObject_ComBox.setObjectName("ServerObject_ComBox")
        self.cSelectSavedFilePath = QtWidgets.QPushButton(self.Client_Tab)
        self.cSelectSavedFilePath.setGeometry(QtCore.QRect(1000, 300, 61, 23))
        self.cSelectSavedFilePath.setObjectName("cSelectSavedFilePath")
        self.FilePath_Input_3 = QtWidgets.QLineEdit(self.Client_Tab)
        self.FilePath_Input_3.setGeometry(QtCore.QRect(710, 300, 271, 23))
        self.FilePath_Input_3.setObjectName("FilePath_Input_3")
        self.Flie_3 = QtWidgets.QLabel(self.Client_Tab)
        self.Flie_3.setGeometry(QtCore.QRect(620, 300, 91, 31))
        self.Flie_3.setObjectName("Flie_3")
        self.tabWidget.addTab(self.Client_Tab, "")
        self.Server = QtWidgets.QWidget()
        self.Server.setObjectName("Server")
        self.ListenAddress_label = QtWidgets.QLabel(self.Server)
        self.ListenAddress_label.setGeometry(QtCore.QRect(650, 70, 101, 16))
        self.ListenAddress_label.setObjectName("ListenAddress_label")
        self.ListenAddress_Input = QtWidgets.QLineEdit(self.Server)
        self.ListenAddress_Input.setGeometry(QtCore.QRect(770, 70, 181, 23))
        self.ListenAddress_Input.setObjectName("ListenAddress_Input")
        self.ListenPort_label = QtWidgets.QLabel(self.Server)
        self.ListenPort_label.setGeometry(QtCore.QRect(670, 110, 81, 20))
        self.ListenPort_label.setObjectName("ListenPort_label")
        self.ListenPort_Input = QtWidgets.QLineEdit(self.Server)
        self.ListenPort_Input.setGeometry(QtCore.QRect(770, 110, 181, 23))
        self.ListenPort_Input.setObjectName("ListenPort_Input")
        self.StartListen_Button = QtWidgets.QPushButton(self.Server)
        self.StartListen_Button.setGeometry(QtCore.QRect(740, 150, 101, 31))
        self.StartListen_Button.setObjectName("StartListen_Button")
        self.StopListen_Button = QtWidgets.QPushButton(self.Server)
        self.StopListen_Button.setGeometry(QtCore.QRect(880, 150, 101, 31))
        self.StopListen_Button.setObjectName("StopListen_Button")
        self.CommunicationLog_label_4 = QtWidgets.QLabel(self.Server)
        self.CommunicationLog_label_4.setGeometry(QtCore.QRect(540, 300, 121, 31))
        self.CommunicationLog_label_4.setObjectName("CommunicationLog_label_4")
        self.scrollArea_11 = QtWidgets.QScrollArea(self.Server)
        self.scrollArea_11.setGeometry(QtCore.QRect(550, 350, 511, 391))
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName("scrollArea_11")
        self.scrollAreaWidgetContents_16 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_16.setGeometry(QtCore.QRect(0, 0, 509, 389))
        self.scrollAreaWidgetContents_16.setObjectName("scrollAreaWidgetContents_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ServerMessageBox = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_16)
        self.ServerMessageBox.setObjectName("ServerMessageBox")
        self.horizontalLayout_16.addWidget(self.ServerMessageBox)
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_16)
        self.ServerState_label = QtWidgets.QLabel(self.Server)
        self.ServerState_label.setGeometry(QtCore.QRect(450, 20, 41, 41))
        self.ServerState_label.setObjectName("ServerState_label")
        self.ServerState = QtWidgets.QLabel(self.Server)
        self.ServerState.setGeometry(QtCore.QRect(500, 30, 141, 21))
        self.ServerState.setObjectName("ServerState")
        self.ServerP_label = QtWidgets.QLabel(self.Server)
        self.ServerP_label.setGeometry(QtCore.QRect(120, 80, 59, 15))
        self.ServerP_label.setObjectName("ServerP_label")
        self.ServerP_Input = QtWidgets.QLineEdit(self.Server)
        self.ServerP_Input.setGeometry(QtCore.QRect(180, 80, 121, 23))
        self.ServerP_Input.setObjectName("ServerP_Input")
        self.ServerG_label = QtWidgets.QLabel(self.Server)
        self.ServerG_label.setGeometry(QtCore.QRect(120, 140, 61, 20))
        self.ServerG_label.setObjectName("ServerG_label")
        self.ServerG_Input = QtWidgets.QLineEdit(self.Server)
        self.ServerG_Input.setGeometry(QtCore.QRect(180, 140, 121, 23))
        self.ServerG_Input.setObjectName("ServerG_Input")
        self.ServerA_label = QtWidgets.QLabel(self.Server)
        self.ServerA_label.setGeometry(QtCore.QRect(120, 210, 59, 15))
        self.ServerA_label.setObjectName("ServerA_label")
        self.ServerA_Input = QtWidgets.QLineEdit(self.Server)
        self.ServerA_Input.setGeometry(QtCore.QRect(182, 200, 121, 23))
        self.ServerA_Input.setObjectName("ServerA_Input")
        self.ServerRandomGenerate_Button = QtWidgets.QPushButton(self.Server)
        self.ServerRandomGenerate_Button.setGeometry(QtCore.QRect(30, 280, 121, 61))
        self.ServerRandomGenerate_Button.setObjectName("ServerRandomGenerate_Button")
        self.ServerGeneratePubKey_Button = QtWidgets.QPushButton(self.Server)
        self.ServerGeneratePubKey_Button.setGeometry(QtCore.QRect(180, 280, 121, 61))
        self.ServerGeneratePubKey_Button.setObjectName("ServerGeneratePubKey_Button")
        self.SendPG2Client_Button = QtWidgets.QPushButton(self.Server)
        self.SendPG2Client_Button.setGeometry(QtCore.QRect(330, 280, 111, 61))
        self.SendPG2Client_Button.setObjectName("SendPG2Client_Button")
        self.LocalPubKey_label_4 = QtWidgets.QLabel(self.Server)
        self.LocalPubKey_label_4.setGeometry(QtCore.QRect(50, 400, 91, 20))
        self.LocalPubKey_label_4.setObjectName("LocalPubKey_label_4")
        self.sClientPubKey_Input = QtWidgets.QPlainTextEdit(self.Server)
        self.sClientPubKey_Input.setGeometry(QtCore.QRect(150, 390, 231, 31))
        self.sClientPubKey_Input.setObjectName("sClientPubKey_Input")
        self.RemotePubKey_label_4 = QtWidgets.QLabel(self.Server)
        self.RemotePubKey_label_4.setGeometry(QtCore.QRect(40, 450, 101, 20))
        self.RemotePubKey_label_4.setObjectName("RemotePubKey_label_4")
        self.sServerPubKey_Input = QtWidgets.QPlainTextEdit(self.Server)
        self.sServerPubKey_Input.setGeometry(QtCore.QRect(150, 440, 231, 31))
        self.sServerPubKey_Input.setObjectName("sServerPubKey_Input")
        self.ServerSendPubKey_Button = QtWidgets.QPushButton(self.Server)
        self.ServerSendPubKey_Button.setGeometry(QtCore.QRect(190, 500, 121, 61))
        self.ServerSendPubKey_Button.setObjectName("ServerSendPubKey_Button")
        self.GeneratedKey_label_4 = QtWidgets.QLabel(self.Server)
        self.GeneratedKey_label_4.setGeometry(QtCore.QRect(40, 590, 91, 20))
        self.GeneratedKey_label_4.setObjectName("GeneratedKey_label_4")
        self.ServerGeneratedPubKey_Output = QtWidgets.QPlainTextEdit(self.Server)
        self.ServerGeneratedPubKey_Output.setGeometry(QtCore.QRect(150, 580, 231, 31))
        self.ServerGeneratedPubKey_Output.setObjectName("ServerGeneratedPubKey_Output")
        self.ServerGenerateKey_Button = QtWidgets.QPushButton(self.Server)
        self.ServerGenerateKey_Button.setGeometry(QtCore.QRect(190, 640, 121, 61))
        self.ServerGenerateKey_Button.setObjectName("ServerGenerateKey_Button")
        self.ClientObject_ComBox = QtWidgets.QComboBox(self.Server)
        self.ClientObject_ComBox.setGeometry(QtCore.QRect(770, 210, 181, 23))
        self.ClientObject_ComBox.setObjectName("ClientObject_ComBox")
        self.ClientObject_label = QtWidgets.QLabel(self.Server)
        self.ClientObject_label.setGeometry(QtCore.QRect(670, 200, 91, 41))
        self.ClientObject_label.setObjectName("ClientObject_label")
        self.Flie_4 = QtWidgets.QLabel(self.Server)
        self.Flie_4.setGeometry(QtCore.QRect(640, 260, 91, 31))
        self.Flie_4.setObjectName("Flie_4")
        self.FilePath_Input_4 = QtWidgets.QLineEdit(self.Server)
        self.FilePath_Input_4.setGeometry(QtCore.QRect(730, 260, 271, 23))
        self.FilePath_Input_4.setObjectName("FilePath_Input_4")
        self.sSelectSavedFilePath = QtWidgets.QPushButton(self.Server)
        self.sSelectSavedFilePath.setGeometry(QtCore.QRect(1010, 260, 61, 23))
        self.sSelectSavedFilePath.setObjectName("sSelectSavedFilePath")
        self.tabWidget.addTab(self.Server, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlainText.setText(_translate("MainWindow", "PlainText:"))
        self.Key.setText(_translate("MainWindow", "Key:"))
        self.Flie.setText(_translate("MainWindow", "File:"))
        self.Algorithm.setText(_translate("MainWindow", "Algorithm:"))
        self.CipherText.setText(_translate("MainWindow", "CipherText:"))
        self.Encrypto_Button.setText(_translate("MainWindow", "Encrypto"))
        self.Caesar_Box.setText(_translate("MainWindow", "Caesar"))
        self.Keyword_Box.setText(_translate("MainWindow", "Keyword"))
        self.Permutation_Box.setText(_translate("MainWindow", "Permutation "))
        self.DoubleTransposition_Box.setText(_translate("MainWindow", "Double-Transposition"))
        self.Vigenere_Box.setText(_translate("MainWindow", "Vigenere"))
        self.Autokey_Box.setText(_translate("MainWindow", "Autokey "))
        self.Playfair_Box.setText(_translate("MainWindow", "Playfair "))
        self.RSA_Box.setText(_translate("MainWindow", "RSA"))
        self.CA_Box.setText(_translate("MainWindow", "CA "))
        self.AES_Box.setText(_translate("MainWindow", "AES"))
        self.SendToServer_Button.setText(_translate("MainWindow", "SendToServer"))
        self.SendToClient_Button.setText(_translate("MainWindow", "SendToClient"))
        self.SelectPlainTextFile.setText(_translate("MainWindow", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Encryption_Tab), _translate("MainWindow", "Encrypttion"))
        self.label_9.setText(_translate("MainWindow", "Algorithm:"))
        self.Caesar_Box_2.setText(_translate("MainWindow", "Caesar"))
        self.Keyword_Box_2.setText(_translate("MainWindow", "Keyword"))
        self.Decrypto_Button.setText(_translate("MainWindow", "Decrypto"))
        self.Permutation_Box_2.setText(_translate("MainWindow", "Permutation "))
        self.AES_Box_2.setText(_translate("MainWindow", "AES"))
        self.Vigenere_Box_2.setText(_translate("MainWindow", "Vigenere"))
        self.Autokey_Box_2.setText(_translate("MainWindow", "Autokey "))
        self.Playfair_Box_2.setText(_translate("MainWindow", "Playfair "))
        self.CA_Box_2.setText(_translate("MainWindow", "CA "))
        self.RSA_Box_2.setText(_translate("MainWindow", "RSA"))
        self.DoubleTransposition_Box_2.setText(_translate("MainWindow", "Double-Transposition"))
        self.CipherText_2.setText(_translate("MainWindow", "CipherText:"))
        self.PlainText_2.setText(_translate("MainWindow", "PlainText:"))
        self.Flie_2.setText(_translate("MainWindow", "File:"))
        self.Key_2.setText(_translate("MainWindow", "Key:"))
        self.SelectCipherTextFile.setText(_translate("MainWindow", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Decryption_Tab), _translate("MainWindow", "Decryption"))
        self.ClientRandomGenerate_Button.setText(_translate("MainWindow", "RandomGenerate"))
        self.ClientGeneratePubKey_Button.setText(_translate("MainWindow", "GeneratePubKey"))
        self.p_label.setText(_translate("MainWindow", "p:"))
        self.g_label.setText(_translate("MainWindow", "g:"))
        self.a_label.setText(_translate("MainWindow", "a:"))
        self.ClientSendPubKey_Button.setText(_translate("MainWindow", "SendPubKey"))
        self.cClientPubKey_label.setText(_translate("MainWindow", "ClientPubKey:"))
        self.ConnectServer_Button.setText(_translate("MainWindow", "ConnectServer"))
        self.RemotePort_label.setText(_translate("MainWindow", "ServerPort:"))
        self.CommunicationLog_label.setText(_translate("MainWindow", "CommunicationLog:"))
        self.DisconnectServer_Button.setText(_translate("MainWindow", "DisconnectServer"))
        self.ClientState_label.setText(_translate("MainWindow", "State:"))
        self.RemotePubKey_label.setText(_translate("MainWindow", "ServerPubKey:"))
        self.GeneratedKey_label.setText(_translate("MainWindow", "GeneratedKey:"))
        self.ClientGenerateKey_Button.setText(_translate("MainWindow", "GenerateKey"))
        self.SendPG2Server_Button.setText(_translate("MainWindow", "SendPG2Server"))
        self.ClientState.setText(_translate("MainWindow", "Nothing...."))
        self.RemoteAddress_label.setText(_translate("MainWindow", "ServerAddress:"))
        self.ServerObject_label.setText(_translate("MainWindow", "ServerObject:"))
        self.cSelectSavedFilePath.setText(_translate("MainWindow", "Select"))
        self.Flie_3.setText(_translate("MainWindow", "SavedFilePath:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Client_Tab), _translate("MainWindow", "Client"))
        self.ListenAddress_label.setText(_translate("MainWindow", "ListenAddress:"))
        self.ListenPort_label.setText(_translate("MainWindow", "ListenPort:"))
        self.StartListen_Button.setText(_translate("MainWindow", "StartListening"))
        self.StopListen_Button.setText(_translate("MainWindow", "StopListening"))
        self.CommunicationLog_label_4.setText(_translate("MainWindow", "CommunicationLog:"))
        self.ServerState_label.setText(_translate("MainWindow", "State:"))
        self.ServerState.setText(_translate("MainWindow", "Nothing...."))
        self.ServerP_label.setText(_translate("MainWindow", "p:"))
        self.ServerG_label.setText(_translate("MainWindow", "g:"))
        self.ServerA_label.setText(_translate("MainWindow", "a:"))
        self.ServerRandomGenerate_Button.setText(_translate("MainWindow", "RandomGenerate"))
        self.ServerGeneratePubKey_Button.setText(_translate("MainWindow", "GeneratePubKey"))
        self.SendPG2Client_Button.setText(_translate("MainWindow", "SendPG2Client"))
        self.LocalPubKey_label_4.setText(_translate("MainWindow", "ClientPubKey:"))
        self.RemotePubKey_label_4.setText(_translate("MainWindow", "ServerPubKey:"))
        self.ServerSendPubKey_Button.setText(_translate("MainWindow", "SendPubKey"))
        self.GeneratedKey_label_4.setText(_translate("MainWindow", "GeneratedKey:"))
        self.ServerGenerateKey_Button.setText(_translate("MainWindow", "GenerateKey"))
        self.ClientObject_label.setText(_translate("MainWindow", "ClientObject:"))
        self.Flie_4.setText(_translate("MainWindow", "SavedFilePath:"))
        self.sSelectSavedFilePath.setText(_translate("MainWindow", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Server), _translate("MainWindow", "Server"))
